### PR TITLE
Lexicon Site wordsmithing

### PR DESCRIPTION
**Pull request by mwilliams2014**
@victorvalle It says that I am unable to automatically merge. I'm not sure if there are conflicts or not, but this was based off of this branch, so hopefully it works. Please let me know if anything else is needed. Thanks!

### CODE REVIEW

**Comment by mwilliams2014** [comment]
Conflict fixed.

**Comment by mwilliams2014** [comment]
@victorvalle regarding the toast descriptions, which is correct?
The toast alerts description has conflicting definitions:

"This type of alert is specific for toast messages. These type of messages appear on the top right corner of the screen. The maximum width of a toast message is 360px, and the height can vary depending on the number of rows. It always has a close action."

"This type of alert must appear at the bottom left side of the screen. There must be a 24px separation from the left and from the bottom. If the alert is temporary, it will disappear in 10 seconds."

**Comment by victorvalle** [comment]
@mwilliams2014  "This type of alert must appear at the bottom left side of the screen. There must be a 24px separation from the left and from the bottom. If the alert is temporary, it will disappear in 10 seconds."

**Comment by mwilliams2014** [comment]
Updated. Thanks!

**Comment by victorvalle** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by victorvalle** [comment]
Hi @mwilliams2014 ! I'm gonna discard your pull. I had issues running the site. The menu items were not unfolding and it was impossible for me to find the bug. So I decided to go file per file taking your changes and make several smaller commits.
I really appreciate the work you have done. Right now it is far easier to read and understand than before :)

**Comment by mwilliams2014** [comment]
Sorry for the bugs. Please let me know what the issue was so I don't do it again in future pulls. Thanks @victorvalle !

**Comment by victorvalle** [comment]
Hi @mwilliams2014 , no problem.
So I think the file was wrong and I still don't know way was the loading indicator. I had to go file per file and test. But I also don't see anything weird in that file. So, I can't tell you what was the error.

**Comment by mwilliams2014** [comment]
Haha. Ok. Well, as long as it's not causing an issue now :-) I wonder if I changed the page URL for that page? I don't think I did, but perhaps that's the case.

**Pull request closed without merging**
